### ISSUE TITLE
MVP Webpage that explains reasons it's important to vote

### ISSUE THREAD

**Issue by drkchn** [drkchn/mosa-upenn-SoC-2023#10]
The webpage will contain information about the importance of elections, democracy, and civic duty to motivate users to vote in their elections. Webpage should be visually appealing while informative for users. Overall, it should provide educational aspects to voting.

**Comment by cfech** [comment]
https://recharts.org/en-US/examples/CustomizedRectangleContent

**Comment by cfech** [comment]
https://stackoverflow.com/questions/61263669/does-material-ui-have-an-image-component

**Comment by cfech** [comment]
https://mui.com/material-ui/react-image-list/

**Comment by drkchn** [comment]
Hi @prinsaa Here are the links to the data for national elections by age, race, sex, etc

Overall graphics: https://www.census.gov/topics/public-sector/voting/library/visualizations.html
https://www.census.gov/library/visualizations/2017/comm/voting-rates-age.html
https://www.census.gov/library/visualizations/2017/comm/voting-rates-race-hispanic.html
https://www.census.gov/library/visualizations/2020/comm/participation-president-election.html
https://www.census.gov/library/visualizations/time-series/demo/voting-historical-time-series.html

Another resource: https://www.electproject.org/election-data/voter-turnout-demographics
https://www.electproject.org/election-data/voter-turnout-data

Raw data: https://www.census.gov/data/tables/time-series/demo/voting-and-registration/voting-historical-time-series.html
