### ISSUE TITLE
Create theme

### ISSUE THREAD

**Issue by cfech** [drkchn/mosa-upenn-SoC-2023#22]

**Comment by cfech** [comment]
Todo:
- [ ] Settle on theme

**Comment by drkchn** [comment]
Working on a sample theme for the home page

**Comment by drkchn** [comment]
Tentatively using the following theme colors for the primary and secondary in the `theme.ts` file
```
export const theme = createTheme({
  palette: {
    primary: {
      main: "#810CA8",
    },
    secondary: {
      main: "#D6C0E6",
    },
  },
});
```

**Comment by cfech** [comment]
Completed: created secondary theme and theme provide for whole app to use
